### ISSUE TITLE
打包成jar包后，java -jar *.jar，提示找不到文件

### ISSUE THREAD

**Issue by jhhe66** [javagossip/dorado#4]
java.io.FileNotFoundException: E:\MyWorks\MyJava\MyDemoJava\nettyclient\target\nettyclient-0.0.1-SNAPSHOT.jar!\BOOT-INF\classes (系统找不到指定的路径。)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:110)
        at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
        at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
        at java.base/java.net.URL.openStream(URL.java:1152)
        at ai.houyi.dorado.rest.util.PackageScanner.scanFromJarProtocol(PackageScanner.java:96)
        at ai.houyi.dorado.rest.util.PackageScanner.scan(PackageScanner.java:47)
        at ai.houyi.dorado.rest.http.impl.Webapp.initialize(Webapp.java:80)
        at ai.houyi.dorado.rest.http.impl.Webapp.create(Webapp.java:57)
        at ai.houyi.dorado.rest.server.DoradoServer.start(DoradoServer.java:59)
        at ai.houyi.dorado.springboot.DoradoAutoConfiguration.lambda$startDoradoServer$0(DoradoAutoConfiguration.java:83)
        at java.base/java.lang.Thread.run(Thread.java:835)
java.io.FileNotFoundException: E:\MyWorks\MyJava\MyDemoJava\nettyclient\target\nettyclient-0.0.1-SNAPSHOT.jar!\BOOT-INF\lib\common-1.0-SNAPSHOT.jar (系统找不到指定的路径。)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:110)
        at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
        at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
        at java.base/java.net.URL.openStream(URL.java:1152)
        at ai.houyi.dorado.rest.util.PackageScanner.scanFromJarProtocol(PackageScanner.java:96)
        at ai.houyi.dorado.rest.util.PackageScanner.scan(PackageScanner.java:47)
        at ai.houyi.dorado.rest.http.impl.Webapp.initialize(Webapp.java:80)
        at ai.houyi.dorado.rest.http.impl.Webapp.create(Webapp.java:57)
        at ai.houyi.dorado.rest.server.DoradoServer.start(DoradoServer.java:59)
        at ai.houyi.dorado.springboot.DoradoAutoConfiguration.lambda$startDoradoServer$0(DoradoAutoConfiguration.java:83)
        at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by jhhe66** [comment]
使用IDEA运行倒是正常的。

**Comment by javagossip** [comment]
已解决，可以用最新版本尝试
